version: '3.8'

services:
  agora-recording:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.docker/output:/usr/src/app/server/output